sudo: required
services:
  - docker

script:
  - docker-compose -f docker-compose-test.yml build
  # Run the postgres entrypoint script so that the DB can get created
  - docker-compose -f docker-compose-test.yml run -d postgres
  - sleep 10  # Make sure the postgres run has enough time to complete.
  - docker-compose -f docker-compose-test.yml run web python3 manage.py test  # Actually run tests
