sudo: required
services:
  - docker

before_script:
  - mkdir postgres-data

script:
  - docker-compose -f docker-compose-test.yml build
  - docker-compose -f docker-compose-test.yml run web python3 manage.py test
